version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=settings.settings
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    restart: unless-stopped

  # 開発用のサービス（オプション）
  web-dev:
    build: .
    ports:
      - "8001:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=settings.settings
      - DEBUG=True
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    command: python manage.py runserver 0.0.0.0:8000
    profiles:
      - dev
