version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=settings.settings
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    restart: unless-stopped

  # 開発用のサービス（オプション）
  web-dev:
    build: .
    ports:
      - "8001:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=settings.settings
      - DEBUG=False
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    command: uvicorn --host 0.0.0.0 --port 8000 settings.asgi:application
    profiles:
      - dev

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles:/app/staticfiles:ro
    restart: unless-stopped
