[project]
name = "bookiniad-com"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django==5.1.7",
    "gunicorn==21.2.0",
    "openai>=0.27.10",
    "openai-agent>=0.1.0",
    "whitenoise==6.6.0",
]
