# Generated by Django 5.1.7 on 2025-08-15 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='宿泊施設名')),
                ('rank', models.IntegerField(default=0, verbose_name='ランク（星数）')),
                ('location', models.CharField(max_length=100, verbose_name='所在地')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('amenities', models.JSONField(default=list, verbose_name='設備・アメニティ')),
                ('image_url', models.URLField(blank=True, verbose_name='画像URL')),
            ],
        ),
        migrations.CreateModel(
            name='Air',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='航空会社名')),
                ('flight_number', models.CharField(max_length=20, verbose_name='便名')),
                ('flight_type', models.CharField(choices=[('domestic', '国内線'), ('international', '国際線')], default='domestic', max_length=20, verbose_name='便種別')),
                ('place_from', models.CharField(max_length=20, verbose_name='出発地')),
                ('place_to', models.CharField(max_length=20, verbose_name='到着地')),
                ('departure_time', models.DateTimeField(verbose_name='出発日時')),
                ('arrival_time', models.DateTimeField(verbose_name='到着日時')),
                ('fee', models.IntegerField(verbose_name='料金')),
                ('available_seats', models.IntegerField(default=100, verbose_name='空席数')),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='セッションID')),
                ('session_type', models.CharField(choices=[('ai_agent', 'AIエージェント'), ('ai_assistant', 'AIアシスタント'), ('rule_bot', 'ルールベースBot')], max_length=20, verbose_name='セッションタイプ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ状態')),
            ],
        ),
        migrations.CreateModel(
            name='StayTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_num_of_people', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('fee_per_people', models.IntegerField(default=1)),
                ('discount_rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('reservation_number', models.AutoField(help_text='予約番号', primary_key=True, serialize=False, unique=True, verbose_name='予約番号')),
                ('from_date', models.DateTimeField(verbose_name='到着予定日時')),
                ('to_date', models.DateTimeField(verbose_name='出発予定時刻')),
                ('num_of_people', models.IntegerField(default=1)),
                ('total_fee', models.IntegerField(default=1)),
                ('place', models.CharField(max_length=30)),
                ('accommodations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.accommodations')),
                ('air', models.ManyToManyField(to='main.air')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'ユーザー'), ('ai_agent', 'AIエージェント'), ('ai_assistant', 'AIアシスタント'), ('rule_bot', 'ルールベースBot')], max_length=20, verbose_name='メッセージタイプ')),
                ('content', models.TextField(verbose_name='メッセージ内容')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
                ('reasoning_process', models.JSONField(blank=True, null=True, verbose_name='推論プロセス')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_time', models.FloatField(verbose_name='応答時間（秒）')),
                ('successful_booking', models.BooleanField(default=False, verbose_name='予約成功')),
                ('user_satisfaction', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='ユーザー満足度（1-5）')),
                ('number_of_turns', models.IntegerField(verbose_name='会話ターン数')),
                ('task_completion_rate', models.FloatField(blank=True, null=True, verbose_name='タスク完了率')),
                ('error_count', models.IntegerField(default=0, verbose_name='エラー回数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='main.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='SearchCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_place', models.CharField(blank=True, max_length=50, null=True, verbose_name='出発地')),
                ('destination_place', models.CharField(blank=True, max_length=50, null=True, verbose_name='目的地')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='出発日')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='帰国日')),
                ('num_of_people', models.IntegerField(blank=True, null=True, verbose_name='人数')),
                ('budget_min', models.IntegerField(blank=True, null=True, verbose_name='最低予算')),
                ('budget_max', models.IntegerField(blank=True, null=True, verbose_name='最高予算')),
                ('preferences', models.JSONField(blank=True, null=True, verbose_name='好み・要望')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_conditions', to='main.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='SystemResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_detected', models.CharField(blank=True, max_length=100, null=True, verbose_name='検出されたインテント')),
                ('confidence_score', models.FloatField(blank=True, null=True, verbose_name='信頼度スコア')),
                ('api_call_info', models.JSONField(blank=True, null=True, verbose_name='API呼び出し情報')),
                ('processing_time', models.FloatField(verbose_name='処理時間')),
                ('response_generated', models.TextField(verbose_name='生成された応答')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_responses', to='main.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='TravelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='パッケージ名')),
                ('description', models.TextField(verbose_name='説明')),
                ('total_price', models.IntegerField(verbose_name='総額')),
                ('stay_duration', models.IntegerField(verbose_name='宿泊日数')),
                ('is_available', models.BooleanField(default=True, verbose_name='予約可能')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.accommodations', verbose_name='宿泊施設')),
                ('outbound_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_packages', to='main.air', verbose_name='往路フライト')),
                ('return_flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_packages', to='main.air', verbose_name='復路フライト')),
            ],
        ),
    ]
