# Generated by Django 5.1.7 on 2025-08-15 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpackage',
            name='accommodation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.accommodations', verbose_name='宿泊施設'),
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='outbound_flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbound_packages', to='main.air', verbose_name='往路フライト'),
        ),
    ]
