# Generated by Django 5.1.7 on 2025-08-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_travelpackage_accommodation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodations',
            name='price_per_night',
            field=models.IntegerField(default=10000, verbose_name='1泊あたりの料金'),
        ),
    ]
