# Generated by Django 5.1.7 on 2025-08-16 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_accommodations_price_per_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodations',
            name='total_rooms',
            field=models.IntegerField(default=50, verbose_name='総部屋数'),
        ),
        migrations.CreateModel(
            name='AccommodationAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('available_rooms', models.IntegerField(verbose_name='空室数')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='main.accommodations')),
            ],
            options={
                'indexes': [models.Index(fields=['accommodation', 'date'], name='main_accomm_accommo_9a177e_idx')],
                'unique_together': {('accommodation', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FlightAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('available_seats', models.IntegerField(verbose_name='空席数')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='main.air')),
            ],
            options={
                'indexes': [models.Index(fields=['flight', 'date'], name='main_flight_flight__f9e82e_idx')],
                'unique_together': {('flight', 'date')},
            },
        ),
    ]
