# Generated by Django 5.1.7 on 2025-08-16 03:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_accommodations_total_rooms_accommodationavailability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reservation_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='予約番号', primary_key=True, serialize=False, unique=True, verbose_name='予約番号'),
        ),
    ]
