# Generated by Django 5.1.7 on 2025-08-17 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_booking_reservation_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, verbose_name='セッションID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('flight', '航空券'), ('accommodation', '宿泊施設'), ('package', 'パッケージ')], max_length=20, verbose_name='アイテムタイプ')),
                ('flight_direction', models.CharField(blank=True, choices=[('outbound', '往路'), ('return', '復路'), ('oneway', '片道')], max_length=20, null=True, verbose_name='航空券方向')),
                ('check_in_date', models.DateField(blank=True, null=True, verbose_name='チェックイン日')),
                ('check_out_date', models.DateField(blank=True, null=True, verbose_name='チェックアウト日')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('unit_price', models.IntegerField(verbose_name='単価')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='追加日時')),
                ('accommodation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.accommodations', verbose_name='宿泊施設')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.cart', verbose_name='カート')),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.air', verbose_name='航空券')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.travelpackage', verbose_name='旅行パッケージ')),
            ],
        ),
    ]
